// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3cy009lxTmOns2kXfNLEgeHTGgKMJK24',
    appId: '1:1006266659079:web:85d6b24b78e00ea02395a2',
    messagingSenderId: '1006266659079',
    projectId: 'usersignin-57ee8',
    authDomain: 'usersignin-57ee8.firebaseapp.com',
    storageBucket: 'usersignin-57ee8.appspot.com',
    measurementId: 'G-VLVN13ZWQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATtDD02D39mBnEAr-xJDZAZYSHAWCmo8U',
    appId: '1:1006266659079:android:11f3ece07f8558e82395a2',
    messagingSenderId: '1006266659079',
    projectId: 'usersignin-57ee8',
    storageBucket: 'usersignin-57ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOfeiIo1U0GRjYn8hyYD623sjqXpgrYuc',
    appId: '1:1006266659079:ios:22ec766e5900ddab2395a2',
    messagingSenderId: '1006266659079',
    projectId: 'usersignin-57ee8',
    storageBucket: 'usersignin-57ee8.appspot.com',
    androidClientId: '1006266659079-gqt0qa5o3vmnj0lkpplqstoadud7r3nf.apps.googleusercontent.com',
    iosClientId: '1006266659079-2bed9clk7312eeoof6ghh2ftmb64pb42.apps.googleusercontent.com',
    iosBundleId: 'com.example.userSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOfeiIo1U0GRjYn8hyYD623sjqXpgrYuc',
    appId: '1:1006266659079:ios:7e68039d57b33e242395a2',
    messagingSenderId: '1006266659079',
    projectId: 'usersignin-57ee8',
    storageBucket: 'usersignin-57ee8.appspot.com',
    androidClientId: '1006266659079-gqt0qa5o3vmnj0lkpplqstoadud7r3nf.apps.googleusercontent.com',
    iosClientId: '1006266659079-frj7oijbogotvor0n4hus21qtf9aa8qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.userSignin.RunnerTests',
  );
}
